# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 386168dcfb9f7794fd32461b776008d8a69a77302784af93de75e1e4b13dcc9aee0a7c847416688120bd3883141638dd62e9df15493cf5a3c996b2188d7220aa

test:
  secret_key_base: 91af57b1a3c5e84d7b3dfe807c87d364deee58d34b7035d5f37b58cf8a734bac47a2cec1b453c1b688bfa302469eab442dc0ffd31bf13f66bb919a4505b284ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
